name: CI

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup update stable
          rustup default stable
          rustup component add clippy
      - run: cargo clippy -- --deny warnings

  rustfmt:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt
      - run: cargo fmt -- --check

  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup update stable
          rustup default stable
          rustup component add clippy rustfmt
      - run: cargo test
